config/routes.rb
Rails.application.routes.draw do

  resources :images

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def new
  end

  def index
    @images = Image.all
  end

  def show
    @image = Image.find(params[:id])
  end


  def create
    @image = Image.new(image_params)

    @image.save
    redirect_to @image
  end

  private
    def image_params
      params.require(:image).permit(:link)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/home/index.html.erb
<div class="welcome">
  <h1>Welcome to <span>Linen</span>, a ruthless, Darwinian image-sharing platform.</h1>
</div>

app/views/images/index.html.erb
<% @images.each do |image| %>
  <div class = "imageContainer">
    <%= image_tag(image.link)%>
  </div>
<% end %>

app/views/images/new.html.erb
<%= form_for :image, url: images_path do |i|%>
    <%= i.text_field :link, :autofocus=>true %>
<% end %>

app/views/images/show.html.erb
<div class="imageContainer">
  <%= image_tag(@image.link)%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Linen</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="board">
        <span></span>
        <span></span>
        <span></span>
        <%= link_to ' ', images_path%>
      </div>
      <h1><%= link_to 'Linen', root_path %></h1>
      <div class="plus">
        <%= link_to '+', new_image_path%>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>